---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
<<<<<<< HEAD
  - name: "updatepippackages-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-fedora}:${tag:-latest}"
=======
  - name: "update_pip_packages-${image:-docker-centos7-ansible}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-docker-centos7-ansible}:${tag:-latest}"
>>>>>>> a6c2bcb65515f2c85068d09b8676eba72477529b
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
<<<<<<< HEAD
=======
  config_options:
    defaults:
      interpreter_python: auto_legacy_silent
      callback_whitelist: profile_tasks
>>>>>>> a6c2bcb65515f2c85068d09b8676eba72477529b
verifier:
  name: ansible
