---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    branches:
      - master
      - main
      - testing
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '41 21 21 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
<<<<<<< HEAD
        uses: actions/checkout@v4
=======
        uses: actions/checkout@v3
>>>>>>> a6c2bcb65515f2c85068d09b8676eba72477529b
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
<<<<<<< HEAD
          - image: "debian-systemd"
            tag: "latest"
          - image: "debian-systemd"
            tag: "bullseye"
          - image: "enterpriselinux"
            tag: "8"
          - image: "fedora-systemd"
            tag: "37"
          - image: "fedora-systemd"
            tag: "latest"
          - image: "docker-opensuse-systemd"
=======
          - image: "debian"
            tag: "buster"
          - image: "debian"
            tag: "bookworm"
          - image: "enterpriselinux"
            tag: "8"
          - image: "fedora"
            tag: "36"
          - image: "fedora"
            tag: "latest"
          - image: "fedora"
            tag: "rawhide"
          - image: "opensuse"
>>>>>>> a6c2bcb65515f2c85068d09b8676eba72477529b
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      # - name: disable apparmor for mysql
      #   run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      # - name: parse apparmor for mysql
      #   run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
<<<<<<< HEAD
        uses: buluma/molecule-action@v5.1.1
=======
        uses: buluma/molecule-action@v5.0.5
>>>>>>> a6c2bcb65515f2c85068d09b8676eba72477529b
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
